# src/main/resources/application.yml
spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: jAadD43eWoig7SpriCgOktftq0bouXdS
            client-secret: 2JKh1bOF-gySUNq7ZJWRzN-ZnjvRy506VfJBgKQs6pZYnyr37Qi0hIulVKwyzNk3
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://dev-2bq3piyn.us.auth0.com/